language: python

python:
 - "3.6"
install:
 - pip install -r ImageCropper/requirements.txt
 - pip install Coverage
script: 
 - cd ImageCropper
 - coverage run ImageCropper.py
 - cd -
 
after_success: coveralls
