language: python

python:
 - "2.6"
before_install:
 - pip install -r ImageCropper/requirements.txt
 - pip install Coverage
 - pip install pytest pytest-cov
 - pip install coveralls
 
script: 
 - cd ImageCropper
 - py.test --cov=ImageCropper test_image.py/
 
after_success: coveralls
