language: python

python:
 - "2.7"
before_install:

 - pip install Coverage
 - pip install pytest pytest-cov
 - pip install coveralls

 - pip install -r parking_classifier/requirements.txt
 
script: 
 - cd ImageCropper
 - cat comvo_1.h5.part* > comvo_1.h5
 - py.test --cov=ImageCropper test_image.py/
 
after_success: coveralls
