language: python

python:
 - "3.6"
before_install:
 - pip install -r ImageCropper/requirements.txt
 - pip install Coverage
 - pip install pytest pytest-cov
 - pip install coveralls
 
script: 
 - cd ImageCropper
 - py.test
 - cd -
 
after_success: coveralls
