language: python

python:
 - "2.7"
before_install:
 - cd ImageCropper
 - pip install -r requirements2.txt
 - cd - 
 - pip install Coverage
 - pip install pytest pytest-cov
 - pip install coveralls
 - apt install libopencv-dev
 - pip3 install opencv-python
 - pip3 install tensorflow
 - pip install keras
 
script: 
 - cd ImageCropper
 - py.test --cov=ImageCropper test_image.py/
 
after_success: coveralls
