
language: python
cache: pip

python:
 - "2.7"
 - "3.6"

install:
  - pip install Coverage pytest pytest-cov coveralls
  - pip install -r ImageCropper/requirements.txt
# - pip install -r parking_classifier/requirements3.txt

before_install:
 - sudo apt-get update
 - ImageCropper/venv/bin/activate
 
script: 
 - cd ImageCropper
 - cat comvo_1.h5.part* > comvo_1.h5
 - py.test --cov=ImageCropper test_image.py
 
after_success: coveralls
